### ISSUE TITLE
Getting error: uninitialized constant #<Class:StreamRails>::Sequel - But using Application Record

### ISSUE THREAD

**Issue by expjazz** [GetStream/stream-rails#111]
I'm getting this error even when using Application Record.

This is the code on my model:
![Screenshot from 2021-04-28 14-08-53](https://user-images.githubusercontent.com/61479648/116444635-4c2cda00-a82b-11eb-8c84-03c11af5dd69.png)

Error message:
![Screenshot from 2021-04-28 14-09-31](https://user-images.githubusercontent.com/61479648/116444700-62d33100-a82b-11eb-86e6-5afbc6d36e96.png)

Thanks!

**Comment by ferhatelmas** [comment]
@expjazz were you able to fix the issue ?

I guess you require pg adapter explicitly. If you have something similar `gem 'sequel_pg', require: false`, remove it.

**Comment by augustosamame** [comment]
Thanks for the quick reply.

Me and @expjazz had a look at the gem code and found that when we referenced non active Record objects (like a field for example) in methods like `activity_actor`, this exception occurred.

This restriction was not well documented and the bug was very cryptic, so putting it here if someone is bitten by this in the future.

**Comment by wujibear** [comment]
This happened to me too.
What is the value of `activity_actor` supposed to be then?

EDIT: In my case my `activity_actor` was optional, so when it was `nil` it got this failure.
