### ISSUE TITLE
Enriching namespaced classes is broken

### ISSUE THREAD

**Issue by andoq** [GetStream/stream-rails#22]
The token for classes is based on ':', however a namespaced model will have ':' in the class name, and so enrichment will fail.

I have a fork where in enrich.rb, instead of splitting the string on ':', I split on:

/(?<!:):(?!:)/

However, I don't have a spec for it, it I get to I'll try and write that and submit a pull sometime this week.

And, it's probably not the best solution - it would be better to use a splitting token is not ':', but something more unique, probably more than one character.  But this would cause compatibility issues with existing users, so probably not a good way to do that.

**Comment by iandouglas** [comment]
Hi @andoq. I know this is a very late reply, but in v 2.5.1 I've written up instructions on how we handle this. Unfortunately right now our enrichment does need to split on a `:` character specifically because that's how many of our feed items are stored (eg, `actor:123`, `verb_name:234`, etc) so to change to something else would be more problematic. In v2.5.2 (or perhaps 2.6) I might introduce some other means of doing deeper enrichment that other customers have asked for. No ETA on this.
