### ISSUE TITLE
FeedConfigException following readme

### ISSUE THREAD

**Issue by tobeee** [GetStream/stream-rails#64]
Hi guys,

I've set up the 4 standard feeds as expected (user,timeline,notification,timeline_aggregated) then proceeded to try and build out the code, but it keeps erroring out on me.

```
feed = StreamRails.feed_manager.get_news_feeds(current_user.id)[:flat]
results = feed.get()['results']
```

Seems to be the issue - [:flat] doesn't seem to work. I tried even making a feed called flat and still no dice. 

Error message is as follows:

```GET https://api.getstream.io/api/v1.0/feed/flat/1/?api_key=zas8wfdv6eyt: 400: FeedConfigException details: The following feeds are not configured: 'flat'. This could be the cause of a typo, but otherwise you should configure them on the dashboard of this app.```

Any idea what could be causing this?

**Comment by dwightgunning** [comment]
In the call to `get_news_feeds` feed you're passing the name of the Feed Group "flat".

Peeking at your app in our admin systems I can see you don't currently have any Feed Group named "flat". Hence the error message "The following feeds are not configured: 'flat'." If you're looking to read one of those existing Feed Groups, you'll just need to change the `:flat` parameter accordingly.

_I'm being deliberately non-specific about your Feed Groups since this is a public repository. Contact support@getstream.io if you need specific details._
